// <auto-generated />
using System;
using AdministradorFincasOrtegaDelgado.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdministradorFincasOrtegaDelgado.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdministradorFincasOrtegaDelgado.Models.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasDefaultValue("Worker")
                    .HasColumnType("character varying(20)");

                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("AdministradorFincasOrtegaDelgado.Models.Siniestro", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("CompaniaSeguros")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<string>("Comunidad")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<string>("DetallesSiniestro")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Estado")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateOnly>("FechaSiniestro")
                    .HasColumnType("date");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("FechaModificacion")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("NumeroCDA")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<string>("Reparador")
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnType("character varying(300)");

                b.Property<string>("ReferenciaSiniestro")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<string>("TelefonoCompania")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<string>("UbicacionDanio")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.HasKey("Id");
                b.ToTable("Siniestros");
            });

            modelBuilder.Entity("AdministradorFincasOrtegaDelgado.Models.Expediente", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Tipo")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)");

                b.Property<DateOnly>("Fecha")
                    .HasColumnType("date");

                b.Property<string>("Comunidad")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<int?>("NumeroComunidad")
                    .HasColumnType("integer");

                b.Property<string>("Ubicacion")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<string>("Descripcion")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("TipoIncidencia")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<string>("Reparadores")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Observaciones")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Estado")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)");

                b.Property<string>("NumeroCDA")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<string>("CompaniaSeguros")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<string>("TelefonoCompania")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<string>("ReferenciaSiniestro")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<int?>("CreadoPorId")
                    .HasColumnType("integer");

                b.Property<string>("CreadoPorNombre")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("timestamp with time zone");

                b.Property<int?>("ModificadoPorId")
                    .HasColumnType("integer");

                b.Property<string>("ModificadoPorNombre")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<DateTime>("FechaModificacion")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");
                b.ToTable("Expedientes");
            });

            modelBuilder.Entity("AdministradorFincasOrtegaDelgado.Models.Incidencia", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Comunidad")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<string>("Descripcion")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Estado")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateOnly>("FechaIncidencia")
                    .HasColumnType("date");

                b.Property<DateTime>("FechaCreacion")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("FechaModificacion")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Observaciones")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Reparador")
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnType("character varying(300)");

                b.Property<string>("Tipo")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<string>("Ubicacion")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.HasKey("Id");
                b.ToTable("Incidencias");
            });

#pragma warning restore 612, 618
        }
    }
}
